### ISSUE TITLE
[BUG] Azure DevOps Pipeline Unable to Navigate to the Specified App

### ISSUE THREAD

**Issue by rtmaus** [Microsoft/EasyRepro#1133]
## Bug Report

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
When executing Easyrepo tests manually in Visual Studio 2019 via the developer command-line our tests are executed and pass - we can run in both standard and headless mode (with screenshots to confirm behavior). When executing via Azure DevOps Pipeline the executing fails with the following error:

```powershell
Test method Cer.Dynamics365.UI.Tests.MsTest.Account.CreateAccount.UCITestCreateAccount threw exception: 
System.InvalidOperationException: App Name Our Service Hub (Test) not found.
  Stack Trace:
      at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass28_0.<OpenApp>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenApp(String appName, Int32 thinkTime)
   at Our.Dynamics365.UI.Tests.MsTest.UciTestBase.ExecuteDefaultTest(Action`1 action) in D:\a\1\s\src\easyrepo\Our.Dynamics365.UI.Tests\MsTest\UciTestBase.cs:line 66
   at Our.Dynamics365.UI.Tests.MsTest.Account.CreateAccount.UCITestCreateAccount() in D:\a\1\s\src\easyrepo\Our.Dynamics365.UI.Tests\MsTest\Account\CreateAccount.cs:line 11
```

An automated test using both SpecFlow and EasyRepo fails at the same step:
```powershell
BrowserAutomation Information: 10001 : Command Start: Open App Our Service Hub (Test) - Attempt 1/2
vstest.console.exe Warning: 0 : Frame AppLandingPage is not loaded. Exception: No frame element found with name or id AppLandingPage
```
**Code to reproduce**  
```csharp
xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);

xrmApp.Navigation.OpenApp(UCIAppName.Sales); //fails at this line

xrmApp.Navigation.QuickCreate("contact");

xrmApp.QuickCreate.SetValue(new LookupItem() { Name = "parentcustomerid", Value = "Test" });

xrmApp.QuickCreate.Save();
```
**Pipeline YAML**

```YAML
trigger:
- none

pool:
  vmImage: 'vs2017-win2016'

variables:
  easyrepoSolution: 'src/easyrepo/*.sln'
  easyrepoSolutionDir: 'src/easyrepo/'
  buildPlatform: 'Any CPU'
  #Build Configurations
  buildConfigurationRelease: 'Release'
  CRMTestServiceSPN: 'Crm-Our-Test'
stages:
- stage: EasyRepo
  displayName: 'EasyRepo Testing'
  jobs:
  - job: easyrepo
    displayName: 'Perform Testing'
    steps:      
        - task: NuGetToolInstaller@1
          displayName: 'Install NuGet Tool'
        - task: NuGetCommand@2
          displayName: 'Nuget Restore EasyRepo Solution'
          inputs:
            restoreSolution: '$(easyrepoSolution)'
        - task: VSBuild@1
          displayName: 'Build EasyRepo Solution'
          inputs:
            solution: '$(easyrepoSolution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfigurationRelease)'
            clean: true
            vsVersion: '15.0'
        - task: VisualStudioTestPlatformInstaller@1
          inputs:
            packageFeedSelector: 'nugetOrg'
            versionSelector: 'latestStable'
        - task: VSTest@2
          displayName: 'Test EasyRepo Solution'
          inputs:
            platform: '$(buildPlatform)'
            configuration: '$(buildConfigurationRelease)'
            searchFolder: '$(easyrepoSolutionDir)\Our.Dynamics365.UI.Tests\bin\Release'
            testRunTitle: 'Test EasyRepo Assemblies'
            uiTests: true
            vsTestVersion: 'toolsInstaller'
            testAssemblyVer2: |
                  **\Our.*test*.dll
                  !**\*TestAdapter.dll
                  !**\obj\*
          continueOnError: true  
        - task: PublishTestResults@2
          displayName: 'Publish Test Results'
          inputs:
           testResultsFormat: VSTest  #change the format to VSTest
           testResultsFiles: |
            **/*.trx
            **/*.jpg
           mergeTestResults: true
           failTaskOnFailedTests: true
           searchFolder: '$(Agent.TempDirectory)' #search the .trx file in $(Agent.TempDirectory)
           publishRunAttachments: true
```
 
**Expected behavior**  
The Pipeline should produce the same results as the execution via the Developer Command Prompt when executing vstest.console.

**Additional context**  
I have attempted to replace the Agent Pool with Windows Latest, removed SpecFlow, changed between standard and headless without any change in the result. Is there different behavior for EasyRepo when run via Pipeline e.g. the TestAdapter?

[logs_12726.zip](https://github.com/microsoft/EasyRepro/files/6463347/logs_12726.zip)
